name: x86_64 build

on: push

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'wassupxP/mingw-builds'
        ref: 'develop'

    - uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Build
      shell: msys2 {0}
      run: >-
        ./build
        --mode=gcc-13.2.0
        --buildroot=/c/buildroot
        --jobs=4
        --rev=0
        --rt-version=v11
        --threads=posix
        --exceptions=seh
        --arch=x86_64
        --static-gcc
        --no-extras
        --enable-languages=c,c++

    - name: List C:/buildtools contents
      shell: msys2 {0}
      run: ls -la /c/buildroot/

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: 'archives'
        path: c:/buildroot/archives/
