name: x86_64 and i686 release builds

on: push

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        threads: [posix]
        exceptions: [seh]
        msvcrt: [msvcrt]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'niXman/mingw-builds'
        ref: 'develop'

    - uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Build
      shell: msys2 {0}
      run: >-
        ./build
        --mode=gcc-13.2.0
        --buildroot=/c/buildroot
        --jobs=8
        --rev=0
        --with-default-msvcrt=${{ matrix.msvcrt }}
        --rt-version=v11
        --threads=${{ matrix.threads }}
        --exceptions=${{ matrix.exceptions }}
        --arch=${{ matrix.arch }}
        --static-gcc
        --bin-compress
        --enable-languages=c,c++

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: 'archives'
        path: c:/buildroot/archives/

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: 'archives'
        path: ./

    - name: Upload to Release
      id: upload_to_release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.7z"
